# Generated by Django 4.1.3 on 2023-04-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingsMLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('szerkezeti_hossz', models.FloatField()),
            ],
        ),
    ]
