# Generated by Django 4.1.3 on 2023-03-21 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0009_alter_artifact_options_alter_date_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateboundwithproject',
            name='employee',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dateboundwithproject',
            name='vehicle',
            field=models.ManyToManyField(blank=True, to='schedule.vehicle'),
        ),
    ]
