# Generated by Django 4.1.3 on 2023-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_dateboundwithproject_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='is_holiday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
