# Generated by Django 4.1.3 on 2023-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_date_is_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
