# Generated by Django 4.1.3 on 2023-03-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_vehicle_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='archived',
        ),
    ]
