# Generated by Django 4.1.3 on 2023-04-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_vehicle_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sit_project',
            name='contract',
            field=models.IntegerField(verbose_name='Szerződés éve'),
        ),
        migrations.AlterField(
            model_name='sit_project',
            name='customer',
            field=models.CharField(max_length=50, verbose_name='Megrendelő'),
        ),
        migrations.AlterField(
            model_name='sit_project',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Helyszín'),
        ),
        migrations.AlterField(
            model_name='sit_project',
            name='project_no',
            field=models.CharField(max_length=30, verbose_name='Iktatószám'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='archived',
            field=models.DateField(blank=True, null=True, verbose_name='Archiválva'),
        ),
    ]
