# Generated by Django 4.1.3 on 2023-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.CharField(max_length=20)),
                ('terulet', models.CharField(max_length=100)),
                ('kivitelezett_hossz', models.FloatField()),
            ],
            options={
                'verbose_name': 'Cölöp',
                'verbose_name_plural': 'Cölöpök',
            },
        ),
    ]
